### ISSUE TITLE
Can this be used stateless?

### ISSUE THREAD

**Issue by sleewok** [marcglasberg/back_button_interceptor#20]
I would like to use this with a stateless widget. Is this possible?

**Comment by marcglasberg** [comment]
Yes! The stateful widget example is used because the `initState` and the `dispose` methods are good places to add/remove the interceptors to coincide with some widget's lifecycle. But as long as you know when to add and remove the interceptors, these are just functions for you to call. For example, if you want an interceptor to exist all the time, you can add it in the app initialization.
