### ISSUE TITLE
Does not call myInterceptor with navigator. maybePop()

### ISSUE THREAD

**Issue by lx36301766** [marcglasberg/back_button_interceptor#3]
The OnWillPop will called if use navigator. maybePop(), but the myInterceptor() on back_button_interceptor is not call

https://github.com/flutter/flutter/issues/31054

**Comment by marcglasberg** [comment]
That's the expected behavior, so I'm going to close this issue. 

The back_button_interceptor is not supposed to replace the Navigator pop. If you have more details on what you want to do, and maybe some example code that shows the problem you are having and the use case for some proposed change, please post it here. Thanks.
